#
# Docker file used in GitHub Actions run unit tests.
#

FROM python:3.8-slim
LABEL maintainer="aheimsbakk@met.no, mortenwh@met.no"

RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    pip install "netCDF4>=1.5,<=1.6" \
                "nose" \
                "mock" \
                "lxml"

VOLUME /src
WORKDIR /src

