#
# Docker file used in GitHub Actions run coverage tests.
#

FROM python:3.8-slim
LABEL maintainer="aheimsbakk@met.no, mortenwh@met.no"

# copy in the requirements
COPY requirements.txt /src/requirements.txt

RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    pip install -r /src/requirements.txt

VOLUME /src
WORKDIR /src

