#
# Docker file used in GitHub Actions run unit tests.
#

FROM python:3.8-slim
LABEL maintainer="aheimsbakk@met.no, mortenwh@met.no"

RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    pip install \
                "confuse" \
                "coverage==5.1" \
                "coveralls>=2" \
                "jinja2" \
                "lxml==4.5" \
                "mock" \
                "netCDF4>=1.5,<=1.6" \
                "nose"

VOLUME /src
WORKDIR /src

