version: '3.4'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    environment:
      CODECOV_TOKEN: "${CODECOV_TOKEN}"
      CI: "${CI}"
      GITHUB_REF: "${GITHUB_REF}"
      GITHUB_SHA: "${GITHUB_SHA}"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    volumes:
      - .:/src
    command: ./tests.sh

