#!/usr/bin/env python
import argparse

from mmd_utils.nc_to_mmd import main


if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument('-i', '--input-file',
                        type=str,
                        dest='input_file',
                        default=None,
                        help="Input file.")
    parser.add_argument('-d', '--output-path',
                        type=str,
                        dest='output_path',
                        default=None,
                        help="Output path.")
    args = parser.parse_args()

    main(input_file=args.input_file, output_path=args.output_path)

#def main():
#    op = ''
#    on = 'multisensor_sic.xml'
#    nc = "http://thredds.met.no/thredds/dodsC/sea_ice/SIW-METNO-ARC-SEAICE_HR-OBS/ice_conc_svalbard_aggregated"
#    md = Nc_to_mmd(op,on,nc)
#    md.to_mmd()
#
#if __name__=='__main__':
#    main()
