#!/usr/bin/env python3

"""
Script to create documentation about netcdf attributes to be used in the Data Management Handbook (DMH; see https://github.com/metno/data-management-handbook).

License:
     This file is part of the py-mmd-tools repository (https://github.com/metno/py-mmd-tools).
     py-mmd-tools is licensed under Apache License 2.0 (https://github.com/metno/py-mmd-tools/blob/master/LICENSE)

Usage: yaml2adoc [-h] -o OUTPUT_FILE
Example: 
    $ python yaml2adoc -o ncattrs.adoc
"""

import sys
import argparse
import pathlib
from py_mmd_tools import nc_to_mmd

def main():
    parser = argparse.ArgumentParser(description="Create an asciidoc file based on https://github.com/metno/py-mmd-tools/tree/master/py_mmd_tools/mmd_elements.yaml.")

    parser.add_argument('-o', '--output_file', help="Output file.")
    args = parser.parse_args()

    if not args.output_file:
        sys.exit()

    adoc = nc_to_mmd.nc_attrs_from_yaml()
    with open(args.output_file, 'w') as fh:
        fh.write(adoc)

if __name__ == '__main__':
    main()
