//// 
{{ data.message }}
////

[[acdd-elements]]
==== Global attributes

In order to add netCDF-CF datasets to the discovery metadata catalog, the data producer should populate the file with certain global attributes mainly described in the Attribute Convention for Data Discovery (ACDD). For a complete description of the ACDD elements, please refer to http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery.

The ACDD recommendations should always be followed in order to properly document your netCDF-CF files. However, the below tables summarize the ACDD and some additional attributes that are needed to properly populate a discovery metadata catalog which fulfills the requirements of international standards (e.g., GCMD/DIF, the WMO profile of ISO19115, etc.).

===== Notes 

*Keywords* describe the content of your dataset following a given vocabulary. It should be provided as a comma separated list with a short name defining the vocabulary used followed by the actual keyword, i.e., ``short_name:keyword``. Example:

[EXAMPLE]
====
:keywords = "GCMDSK:Earth Science > Atmosphere > Atmospheric radiation, NORTHEMES:Weather and climate" ;
====

In addition, ``keywords_vocabulary`` provides information about the vocabulary defining the keywords. Example:

[EXAMPLE]
====
:keywords_vocabulary = "GCMDSK:GCMD Science Keywords:https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/sciencekeywords, GCMDPROV:GCMD Providers:https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/providers, GCMDLOC:GCMD Locations:https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/locations" ;
====

See https://adc.met.no/node/96 for more information about how to define the ACDD keywords.

A data *license* provides information about any restrictions on the use of the dataset. To support a linked data approach, the ``license`` element should be supported by a ``license_resource`` element, providing a link to the license definition. Example:

[EXAMPLE]
====
:license = "CC-BY-4.0" ; +
:license_resource = "http://spdx.org/licenses/CC-BY-4.0" ;
====

===== List of Attributes

This section provides lists of ACDD elements that are required and recommended, as well as some extra elements that are needed to fully support our data management needs. The right columns of these tables provide the https://htmlpreview.github.io/?https://github.com/metno/mmd/blob/master/doc/mmd-specification.html[MET Norway Metadata Specification (MMD)] fields that map to the ACDD (and our extension to ACDD) elements. Please refer to https://htmlpreview.github.io/?https://github.com/metno/mmd/blob/master/doc/mmd-specification.html[MMD] for definitions of these elements, as well as controlled vocabularies that should be used.

The following ACDD elements are required:
[cols=",,"]
|=======================================================================
|*ACDD Attribute* |*Repetition* |*MMD equivalent*
{% for elem in data['acdd']['required'] %}
    {% if elem['attribute'] | is_list %}
        {% for subelem in elem['attribute'] %}
|{{ subelem }} | {{ elem['repetition_str'] }} | {{ elem['mmd_field'] }}
        {% endfor %}
    {% else %}
|{{ elem['attribute'] }} | {{ elem['repetition_str'] }} | {{ elem['mmd_field'] }}
{% endif %}
{% endfor %}
|=======================================================================

The following ACDD elements are recommended:
[cols=",,,"]
|=======================================================================
|*ACDD Attribute* |*Repetition* |*Default* |*MMD equivalent*
{% for elem in data['acdd']['not_required'] %}
    {% if elem[0] | is_list %}
        {% for subelem in elem[0] %}
|{{ subelem }} | {{ elem['repetition_str'] }} | {{ elem['default'] }} | {{ elem['mmd_field'] }}
        {% endfor %}
    {% else %}
|{{ elem['attribute'] }} | {{ elem['repetition_str'] }} | {{ elem['default'] }} | {{ elem['mmd_field'] }}
{% endif %}
{% endfor %}
|=======================================================================

The following elements are ACDD extensions that are needed to improve (meta)data interoperability. Please refer to the documentation of https://htmlpreview.github.io/?https://github.com/metno/mmd/blob/master/doc/mmd-specification.html[MMD] for more details:
[cols=",,"]
|=======================================================================
|*Extra Attribute* |*Default* |*MMD equivalent*
{% for elem in data['acdd_ext'] %}
|{{ elem['attribute'] }} | {{ elem['default'] }} | {{ elem['mmd_field'] }}
{% endfor %}
|=======================================================================
