name: flake8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkSyntax:
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install flake8
        run: pip install flake8
      - name: Syntax Error Check
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Code Style Check
        run: flake8 . --count --max-line-length=99 --ignore E221,E226,E228,E241 --show-source --statistics
