name: tests

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: run unit tests
      run: |
        docker-compose -f docker-compose.unittests.yml up --exit-code-from unittests
